// Code generated by apigear.io DO NOT EDIT


export interface IClient {
    setProperty(key: string, value: any): void;
    getProperty(key: string): any;
    onPropertyChanged(property: string, listener: (value: any) => void): void;
    
    getState(): { [key: string]: any };
    setState(properties: { [key: string]: any }): void;

    callMethod(key: string, ...args: any[]): any;
    onMethodCalled(key: string, listener: (...args: any[]) => any): void;

    emitSignal(signal: string, ...args: any[]): void;
    onSignal(signal: string, listener: (...args: any[]) => void): void;
}

export interface IChannel {
    createClient(objectId: string): IClient
}

declare global {
    declare function $createChannel(url = "ws://localhost:5555/ws"): IChannel;
}
