// Code generated by apigear.io DO NOT EDIT

import type { IClient } from "./global.stim"

{{- range .Module.Enums }}
// enum declaration for {{.Name}}
export enum {{Camel .Name}} {
    {{- range .Members}}
    {{SNAKE .Name}} = {{.Value}},
    {{- end}}
}
{{- end }}

{{- range .Module.Structs }}
// struct declaration for {{.Name}}
export interface {{Camel .Name}} {
    {{- range .Fields}}
    {{camel .Name}}: {{tsType "" .}};
    {{- end}}
}
{{- end }}

{{- range .Module.Interfaces }}
export const {{camel .Name}}: IClient
{{- end }}


