// Code initially generated by apigear.io. THIS IS USER EDITABLE

const {
{{- range .Module.Enums}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Structs}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Interfaces}}
  {{camel .Name}},
{{- end}}
} = require("api/{{dot .Module.Name}}.js")  


const channel = $createChannel()

{{- range .Module.Interfaces}}
{{ $class := camel .Name}}
const {{ $class }} = channel.createClient("{{dot $.Module.Name}}.{{Camel .Name}}")
// {{ $class }}.setProperty("count", 10)
// {{ $class }}.onProperty("count", function(v) {
  console.log("count is ", v)
})
// {{ $class }}.callMethod("increment")
// {{ $class }}.callMethod("decrement", 2)
// {{ $class }}.onSignal("minReached", function() {
//  console.log("min reached")
//})
{{- end }}