version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  serve:
    description: "Run ApiGear CLI in serve mode"
    cmds:
      - apigear serve
  ivi:clean:
    description: "Clean simulation code"
    cmds:
      - rm -rf examples/ivituner/simulation
  ivi:build:
    description: "Build simulation code"
    cmds:
      - apigear generate solution examples/ivituner/ivi.solution.yaml
  ivi:run:
    description: "Run simulation code"
    cmds:
      - apigear simulate run examples/ivituner/simulation/ivi.tuner.script.js