version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  serve:
    cmds:
      - apigear serve
  ivi:clean:
    cmds:
      - rm -rf examples/ivituner/simulation
  ivi:build:
    cmds:
      - apigear generate solution examples/ivituner/ivi.solution.yaml
  ivi:run:
    cmds:
      - apigear sim run examples/ivituner/simulation/ivi.tuner.script.sim.js --serve

  demo:clean:
    cmds:
      - rm -rf examples/demo/simulation
  demo:build:
    cmds:
      - apigear generate solution examples/demo/demo.solution.yaml
  demo:run:
    cmds:
      - apigear sim run examples/demo/simulation/counter.script.sim.js --serve