// Code initially generated by apigear.io. THIS IS USER EDITABLE
console.log("demo.script.sim.js")
const {
  counter,
} = require("api/demo.sim.js")

console.log("counter", counter)
counter.increment = function() {
  counter.count++
  console.log("increment", this.count)
}
counter.clear = function() {
  counter.$.emitSignal("cleared")
  counter.count = 0
  console.log("clear", this.count)
}

counter.$.onProperty("count", function(value) {
  console.log("count", value)
})

counter.$.onSignal("cleared", function() {
  console.log("signal cleared")
})

// function main() {
//   const service = $.createService("demo.Counter", {
//     count: 0,
//   })
//   for (let i = 0; i < 5; i++) {
//     service.callMethod("increment")
//   }
//   service.callMethod("clear")
//   console.log("main functions are auto called from the simulator")
// }

// function demo() {
//   console.log("other top level functions can be called from the simulator")
// }