// Code initially generated by apigear.io. THIS IS USER EDITABLE

const {
  counter,
} = require("api/demo.js")

counter.increment = function() {
  console.log("increment(...)")
}
counter.clear = function() {
  console.log("clear(...)")
}