// Code initially generated by apigear.io. THIS IS USER EDITABLE

const {
{{- range .Module.Enums}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Structs}}
  {{Camel .Name}},
{{- end}}
} = require("./api/{{dot .Module.Name}}")  

// Client module to call the server API

// a new connection channel to the server
const channel = $createChannel("ws://localhost:5555/ws")


{{- range .Module.Interfaces}}
{{ $class := camel .Name}}
// Create a client for the interface {{.Name}}
const {{ $class }} = channel.createClient("{{dot $.Module.Name}}.{{Camel .Name}}")

function set{{ Camel $class }}Default() {
  console.log("Setting properties for {{camel .Name}}")
  {{- range .Properties }}
  {{ $class }}.setProperty("{{.Name}}", {{jsDefault "" .}})
  {{- end }}
}
{{- range .Operations }}
// {{ $class }}.callMethod("{{camel .Name}}", ...)
{{- end }}
{{- range .Signals }}
{{ $class }}.onSignal("{{camel .Name}}", function({{jsParams "" .Params}}) {
  console.log("received signal {{camel .Name}} with params: ", {{jsParams "" .Params}})
})
{{- end }}
{{- end }}

function main() {
  console.log("main functions are auto called from the simulator")
  {{- range .Module.Interfaces }}
  {{- $class := camel .Name}}
  set{{ Camel $class }}Default()
  {{- end }}
}