// Code initially generated by apigear.io. THIS IS USER EDITABLE

const {
{{- range .Module.Enums}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Structs}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Interfaces}}
  $create{{Camel .Name}},
{{- end}}
} = require("./api/{{dot .Module.Name}}.js")  

{{- range .Module.Interfaces }}
{{ $class := camel .Name}}

const {{ $class }} = $create{{Camel .Name}}({
{{- range .Properties}}
  {{.Name}}: {{jsDefault "" .}},
{{- end}}
})

{{- range .Operations }}

{{ $class }}.{{camel .Name}} = function({{jsParams "" .Params}}) {
  console.log("{{.Name}}(...)")
  {{- if .Return.IsNotVoid }}
  return {{ .Return.Name }}
  {{- else }}
  {{- end }}
}
{{- end }}


{{- range .Signals }}
{{ $class }}.emit{{Camel .Name}} = function({{jsParams "" .Params}}) {
  console.log("emit {{camel .Name}}(...)")
  this.emit("{{camel .Name}}", {{jsParams "" .Params}})
}
{{- end }}
{{- end }}


function main() {
  console.log("main functions are auto called from the simulator")
}
