// Code generated by apigear.io DO NOT EDIT


export interface IService {
    setProperty(key: string, value: any): void;
    getProperty(key: string): any;
    emitPropertyChanged(property: string, value: any): void;
    onPropertyChanged(property: string, listener: (...args: any[]) => void): void;
    setState(properties: Record<string, any>): void;
    getState(): Record<string, any>;
    setMethod(key: string, method: (...args: any[]) => any): void;
    callMethod(key: string, ...args: any[]): any;
    onMethodCalled(method: string, listener: (...args: any[]) => void): void;
    emitSignal(signal: string, ...args: any[]): void;
    onSignal(signal: string, listener: (...args: any[]) => void): void;
}


declare function $createService(objectId : string, state: Record<string, any>): IService;
declare function $createServiceProxy(objectId : string, state: Record<string, any>): IService;
declare function $getService(objectId : string): IService;