// Code generated by apigear.io DO NOT EDIT


export interface IService {
    setProperty(key: string, value: unknown): void;
    getProperty(key: string): unknown;
    emitPropertyChanged(property: string, value: unknown): void;
    onPropertyChanged(property: string, listener: (...args: unknown[]) => void): void;
    setState(properties: Record<string, unknown>): void;
    getState(): Record<string, unknown>;
    setMethod(key: string, method: (...args: unknown[]) => unknown): void;
    callMethod(key: string, ...args: unknown[]): unknown;
    onMethodCalled(method: string, listener: (...args: unknown[]) => void): void;
    emitSignal(signal: string, ...args: unknown[]): void;
    onSignal(signal: string, listener: (...args: unknown[]) => void): void;
}


declare global {
    declare function $quit(): void
    declare function $createService(objectId : string, state: Record<string, unknown>): IService;
    declare function $createServiceProxy(objectId : string, state: Record<string, unknown>): IService;
    declare function $getService(objectId : string): IService;
}