// Code generated by apigear.io DO NOT EDIT

import { IService } from "./global.sim";

{{- range .Module.Enums }}
// enum declaration for {{.Name}}
export enum {{Camel .Name}} {
    {{- range .Members}}
    {{SNAKE .Name}} = {{.Value}},
    {{- end}}
}
{{- end }}

{{- range .Module.Structs }}
// struct declaration for {{.Name}}
export interface {{Camel .Name}} {
    {{- range .Fields}}
    {{camel .Name}}: {{tsType "" .}};
    {{- end}}
}
{{- end }}

{{- range .Module.Interfaces }}
// interface declaration for {{.Name}}
export interface I{{Camel .Name}} {
    $: IService
    {{- range .Properties}}
    {{camel .Name}}: {{tsType "" .}};
    {{- end}}
    {{- range .Operations}}
    {{camel .Name}}({{tsParams "" .Params}}): {{tsReturn "" .Return}};
    {{- end}}
    {{- range .Signals}}
    emit{{Camel .Name}}({{tsParams "" .Params}}): void;
    {{- end }}
}

export const {{camel .Name}}: I{{Camel .Name}}

{{- end }}

