// Code initially generated by apigear.io. THIS IS USER EDITABLE

const {
{{- range .Module.Enums}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Structs}}
  {{Camel .Name}},
{{- end}}
{{- range .Module.Interfaces}}
  {{camel .Name}},
{{- end}}
} = require("api/{{dot .Module.Name}}.sim.js")  


{{- range .Module.Interfaces}}
{{ $class := camel .Name}}
{{- range .Operations}}
{{ $class }}.{{camel .Name}} = function({{jsParams "" .Params}}) {
  console.log("{{camel .Name}}(...)")
}
{{- end }}
{{- end }}


function main() {
  console.log("main functions are auto called from the simulator")
}

function demo() {
  console.log("other top level functions can be called from the simulator")
}