// Code generated by apigear.io DO NOT EDIT


export interface IService {
    setProperty(key: string, value: unknown): void;
    getProperty(key: string): unknown;
    emitPropertyChanged(property: string, value: unknown): void;
    onPropertyChanged(property: string, listener: (...args: unknown[]) => void): void;
    setState(properties: Record<string, unknown>): void;
    getState(): Record<string, unknown>;
    setMethod(key: string, method: (...args: unknown[]) => unknown): void;
    callMethod(key: string, ...args: unknown[]): unknown;
    onMethodCalled(method: string, listener: (...args: unknown[]) => void): void;
    emitSignal(signal: string, ...args: unknown[]): void;
    onSignal(signal: string, listener: (...args: unknown[]) => void): void;
}

declare global {
    function $quit(): void
    function $createService(objectId : string, state: Record<string, unknown>): IService;
    function $createServiceProxy(objectId : string, state: Record<string, unknown>): IService;
    function $getService(objectId : string): IService;
}

// stimulation global definitions

export interface IClient {
    setProperty(key: string, value: any): void;
    getProperty(key: string): any;
    onPropertyChanged(property: string, listener: (value: any) => void): void;
    
    getState(): { [key: string]: any };
    setState(properties: { [key: string]: any }): void;

    callMethod(key: string, ...args: any[]): any;
    onMethodCalled(key: string, listener: (...args: any[]) => any): void;

    emitSignal(signal: string, ...args: any[]): void;
    onSignal(signal: string, listener: (...args: any[]) => void): void;
}

export interface IChannel {
    createClient(objectId: string): IClient
}

declare global {
    function $createChannel(url: string): IChannel;
}