// Code generated by apigear.io DO NOT EDIT

{{- range .Module.Enums }}
const {{Camel .Name}} = {
  {{- range .Members}}
  {{.Name}}: {{.Value}},
  {{- end}}
}
{{- end }}

{{- range .Module.Structs }}
class {{.Name}} {
  constructor() {
  {{- range .Fields}}
    this.{{.Name}} = {{jsDefault "" .}}
  {{- end}}
  }
}
{{- end }}

{{- range .Module.Interfaces }}
{{ $class := camel .Name}}

const $create{{Camel .Name}} = function(properties = {}) {
  return $createService("{{dot $.Module.Name}}.{{Camel .Name}}", properties)
}

const {{ $class }} = $createService("{{dot $.Module.Name}}.{{Camel .Name}}", {
{{- range .Properties}}
  {{.Name}}: {{jsDefault "" .}},
{{- end}}
})

{{- range .Operations }}

{{ $class }}.{{camel .Name}} = function({{jsParams "" .Params}}) {
  console.log("{{camel .Name}}(...)")
  {{- if .Return.IsNotVoid }}
  return {{ camel .Return.Name }}
  {{- else }}
  {{- end }}
}
{{- end }}


{{- range .Signals }}
{{ $class }}.emit{{Camel .Name}} = function({{jsParams "" .Params}}) {
  console.log("emit {{camel .Name}}(...)")
  this.emit("{{camel .Name}}", {{jsParams "" .Params}})
}
{{- end }}
{{- end }}


module.exports = {
{{- range .Module.Enums }}
  {{Camel .Name}},
{{- end }}
{{- range .Module.Structs }}
  {{.Name}},
{{- end }}
{{- range .Module.Interfaces }}
  {{camel .Name}},
  $create{{Camel .Name}},
{{- end }}
}

