// Code generated by apigear.io DO NOT EDIT

{{- range .Module.Enums }}
const {{Camel .Name}} = {
  {{- range .Members}}
  {{.Name}}: {{.Value}},
  {{- end}}
}
{{- end }}

{{- range .Module.Structs }}
class {{.Name}} {
  constructor() {
  {{- range .Fields}}
    this.{{.Name}} = {{jsDefault "" .}}
  {{- end}}
  }
}
{{- end }}

{{- range .Module.Interfaces }}
{{ $class := camel .Name}}

const $create{{Camel .Name}} = function(properties = {}) {
  return $createService("{{$.Module.Name}}.{{Camel .Name}}", properties)
}
{{- end }}

module.exports = {
{{- range .Module.Enums }}
  {{Camel .Name}},
{{- end }}
{{- range .Module.Structs }}
  {{.Name}},
{{- end }}
{{- range .Module.Interfaces }}
  $create{{Camel .Name}},
{{- end }}
}

